name: my-custom-env
channels:
  - conda-forge
  - defaults
dependencies:
  - anaconda::libtiff
  - python=3.8
  - netCDF4
  - cartopy=0.19.0
  - matplotlib=3.5.2
  - xarray
  - jupyter
  - metpy
  - cfgrib
